# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        cd thingifier-tests
        pipx install poetry
        poetry install
    - name: Test with pytest
      run: |
        cd Application_Being_Tested
        java -jar runTodoManagerRestAPI-1.5.5.jar & 
        cd ../thingifier-tests
        sleep 5
        poetry run pytest -s -v --random-order
      continue-on-error: true
    - name: Format Code
      run: |
        cd thingifier-tests
        poetry run black .
